# Generated by Django 6.0.5 on 2026-05-07 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0004_travelbooking'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='google_map_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
